function birthstones (text: string, text2: string) {
    for (let Month = 0; Month <= monthList.length - 1; Month++) {
        if (monthList[Month] == text) {
            game.splash(birthstoneList[Month])
        } else {
            game.splash("Error. Try Again")
        }
    }
    for (let Month = 0; Month <= monthList.length - 1; Month++) {
        if (monthList[Month] == text2) {
            game.splash(flowerList[Month])
        } else {
            game.splash("Error. Try Again")
        }
    }
}
let flowerList: string[] = []
let birthstoneList: string[] = []
let monthList: string[] = []
scene.setBackgroundImage(img`
    fffffffffffffffffffffff1fffffffff2ff55fffeeffffffff44ffffffffffffffffcccccccccccccccccccccffffffffffffffffff44ffffffffeefff55ff2fffffff1ffffffffffffffffffffffff
    ffffffffffffffffffffff1ffffffff22ff5ffffeffffffff44fffffffffffffcccccfffffffffffffffffffffcccccfffffffffffffff44ffffffffeffff5ff22ffffff1fffffffffffffffffffffff
    fffffffffffffffffffff1ffffffff2fff5fffeefffffff44ffffffffffffcccfffffffffffffffffffffffffffffffcccffffffffffffff44fffffffeefff5fff2ffffff1ffffffffffffffffffffff
    ffffffffffffffffffff1ffffffff2ff55fffeffffffff4fffffffffffcccfffffffffffffffffffffffffffffffffffffcccfffffffffffff4ffffffffefff55ff2ffffff1fffffffffffffffffffff
    ffffffffffffffffffff1fffffff2ff5ffffefffffff44ffffffffffccfffffffffffffffffffffffffffffffffffffffffffccffffffffffff44fffffffeffff5ff2fffff1fffffffffffffffffffff
    fffffffffffffffffff1fffffff2ff5ffffefffffff4ffffffffffccfffffffffffffaaaaaaaaaaaaaaaaaaaaafffffffffffffccffffffffffff4fffffffeffff5ff2fffff1ffffffffffffffffffff
    ffffffffffffffffff1fffffff2ff5ffffeffffff44fffffffffccfffffffffffaaaafffffffffffffffffffffaaaafffffffffffccfffffffffff44ffffffeffff5ff2fffff1fffffffffffffffffff
    fffffffffffffffff1fffffff2ff5ffffeffffff4fffffffffccffffffffffaaafffffffffffffffffffffffffffffaaaffffffffffccfffffffffff4ffffffeffff5ff2fffff1ffffffffffffffffff
    ffffffffffffffff1fffffff2ff5ffffeffffff4ffffffffccfffffffffaaafffffffffffffffffffffffffffffffffffaaafffffffffccffffffffff4ffffffeffff5ff2fffff1fffffffffffffffff
    fffffffffffffff1fffffff2ff5ffffeffffff4ffffffffcfffffffffaafffffffffffffffffffffffffffffffffffffffffaafffffffffcffffffffff4ffffffeffff5ff2fffff1ffffffffffffffff
    fffffffffffffff1ffffff2ff5ffffeffffff4fffffffccffffffffaafffffffffffffffffffffffffffffffffffffffffffffaaffffffffccfffffffff4ffffffeffff5ff2ffff1ffffffffffffffff
    ffffffffffffff1fffffff2ff5fffeffffff4fffffffcffffffffaafffffffffffffff8888888888888888888fffffffffffffffaaffffffffcfffffffff4ffffffefff5ff2fffff1fffffffffffffff
    fffffffffffff1fffffff2ff5fffeffffff4fffffffcfffffffaafffffffffffff8888fffffffffffffffffff8888fffffffffffffaafffffffcfffffffff4ffffffefff5ff2fffff1ffffffffffffff
    fffffffffffff1ffffff2ff5fffeffffff4ffffffccfffffffaffffffffffff888fffffffffffffffffffffffffff888ffffffffffffafffffffccffffffff4ffffffefff5ff2ffff1ffffffffffffff
    ffffffffffff1ffffff2ff5fffeffffff4ffffffcfffffffaaffffffffff888fffffffffffffffffffffffffffffffff888ffffffffffaafffffffcffffffff4ffffffefff5ff2ffff1fffffffffffff
    fffffffffff1fffffff2ff5ffeffffff4ffffffcfffffffaffffffffff88fffffffffffffffffffffffffffffffffffffff88ffffffffffafffffffcffffffff4ffffffeff5ff2fffff1ffffffffffff
    fffffffffff1ffffff2ff5ffeffffff4ffffffcfffffffafffffffff88fffffffffffffffffffffffffffffffffffffffffff88fffffffffafffffffcffffffff4ffffffeff5ff2ffff1ffffffffffff
    ffffffffff1ffffff2ff5fffefffff4ffffffcffffffaaffffffff88fffffffffffffffffffffffffffffffffffffffffffffff88ffffffffaaffffffcffffffff4fffffefff5ff2ffff1fffffffffff
    ffffffffff1ffffff2f5fffefffff4ffffffcffffffafffffffff8fffffffffffffffffffffffffffffffffffffffffffffffffff8fffffffffaffffffcffffffff4fffffefff5f2ffff1fffffffffff
    fffffffff1ffffff2ff5ffefffff4ffffffcffffffaffffffff88fffffffffffffffffffffffffffffffffffffffffffffffffffff88ffffffffaffffffcffffffff4fffffeff5ff2ffff1ffffffffff
    fffffffff1fffff2ff5fffefffff4fffffcffffffaffffffff8ffffffffffffffffffff6666666666666666666ffffffffffffffffff8ffffffffaffffffcfffffff4fffffefff5ff2fff1ffffffffff
    ffffffff1ffffff2ff5ffefffff4ffffffcfffffaffffffff8ffffffffffffffffff666fffffffffffffffffff666ffffffffffffffff8ffffffffafffffcffffffff4fffffeff5ff2ffff1fffffffff
    ffffffff1fffff2ff5ffefffff4ffffffcfffffafffffff88ffffffffffffffff666fffffffffffffffffffffffff666ffffffffffffff88fffffffafffffcffffffff4fffffeff5ff2fff1fffffffff
    fffffff1ffffff2f5fffefffff4fffffcfffffafffffff8ffffffffffffffff66fffffffffffffffffffffffffffffff66ffffffffffffff8fffffffafffffcfffffff4fffffefff5f2ffff1ffffffff
    fffffff1fffff2ff5ffefffff4fffffcffffffaffffff8fffffffffffffff66fffffffffffffffffffffffffffffffffff66fffffffffffff8ffffffaffffffcfffffff4fffffeff5ff2fff1ffffffff
    ffffff1ffffff2f5fffeffff4ffffffcfffffaffffff8ffffffffffffff66fffffffffffffffffffffffffffffffffffffff66ffffffffffff8ffffffafffffcffffffff4ffffefff5f2ffff1fffffff
    ffffff1fffff2ff5ffefffff4fffffcfffffaffffff8fffffffffffff66fffffffffffffffffffffffffffffffffffffffffff66fffffffffff8ffffffafffffcfffffff4fffffeff5ff2fff1fffffff
    fffff1ffffff2f5fffeffff4fffffcfffffaffffff8fffffffffffff6fffffffffffffffffffffffffffffffffffffffffffffff6fffffffffff8ffffffafffffcfffffff4ffffefff5f2ffff1ffffff
    fffff1fffff2ff5ffefffff4fffffcfffffaffffff8ffffffffffff6fffffffffffffffffffffffffffffffffffffffffffffffff6ffffffffff8ffffffafffffcfffffff4fffffeff5ff2fff1ffffff
    fffff1fffff2ff5ffeffff4fffffcfffffaffffff8fffffffffff66fffffffffffffffffffffffffffffffffffffffffffffffffff66fffffffff8ffffffafffffcfffffff4ffffeff5ff2fff1ffffff
    ffff1fffff2ff5ffefffff4fffffcffffaffffff8fffffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffffffff8ffffffaffffcfffffff4fffffeff5ff2fff1fffff
    ffff1fffff2ff5ffeffff4fffffcfffffafffff8fffffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffffffff8fffffafffffcfffffff4ffffeff5ff2fff1fffff
    ffff1ffff2ff5fffeffff4fffffcffffaffffff8ffffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffffff8ffffffaffffcfffffff4ffffefff5ff2ff1fffff
    fff1fffff2ff5ffeffff4fffffcfffffafffff8ffffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffffff8fffffafffffcfffffff4ffffeff5ff2fff1ffff
    fff1fffff2ff5ffeffff4fffffcffffafffff8ffffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffffff8fffffaffffcfffffff4ffffeff5ff2fff1ffff
    fff1ffff2ff5ffefffff4ffffcfffffafffff8ffffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffffff8fffffafffffcffffff4fffffeff5ff2ff1ffff
    ff1fffff2ff5ffeffff4fffffcffffafffff8ffffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffffff8fffffaffffcfffffff4ffffeff5ff2fff1fff
    ff1fffff2ff5ffeffff4ffffcfffffafffff8fffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffffff8fffffafffffcffffff4ffffeff5ff2fff1fff
    ff1ffff2ff5ffefffff4ffffcffffafffff8fffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffffff8fffffaffffcffffff4fffffeff5ff2ff1fff
    ff1ffff2ff5ffeffff4fffffcffffafffff8fffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffffff8fffffaffffcfffffff4ffffeff5ff2ff1fff
    f1fffff2ff5ffeffff4ffffcfffffaffff8fffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffffff8ffffafffffcffffff4ffffeff5ff2fff1ff
    f1fffff2ff5ffeffff4ffffcffffafffff8fffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffffff8fffffaffffcffffff4ffffeff5ff2fff1ff
    f1ffff2ff5ffeffff4fffffcffffafffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8fffffaffffcfffffff4ffffeff5ff2ff1ff
    f1ffff2ff5ffeffff4ffffcfffffaffff8fffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffffff8ffffafffffcffffff4ffffeff5ff2ff1ff
    f1ffff2ff5ffeffff4ffffcffffafffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8fffffaffffcffffff4ffffeff5ff2ff1ff
    1fffff2ff5ffeffff4ffffcffffafffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8fffffaffffcffffff4ffffeff5ff2fff1f
    1fffff2f5fffeffff4ffffcffffaffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8ffffaffffcffffff4ffffefff5f2fff1f
    1ffff2ff5ffeffff4fffffcffffaffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8ffffaffffcfffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffafffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8fffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffafffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8fffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1f
    1ffff2ff5ffeffff4fffffcffffaffff8ffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffff8ffffaffffcfffffff4ffffeff5ff2ff1f
    f1fff2ff5fffeffff4ffffcffffaffff8ffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffff8ffffaffffcffffff4ffffefff5ff2f1ff
    f1fff2fff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5fff2f1ff
    f1ffff2ff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5ff2ff1ff
    f1ffff2ff5ffeffff4ffffcfffffaffff8ffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffff8ffffafffffcffffff4ffffeff5ff2ff1ff
    f1ffff2ff5ffeffff4fffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcfffffff4ffffeff5ff2ff1ff
    ff1fff2fff5ffeffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4ffffeff5fff2f1fff
    ff1fff2fff5ffeffff4ffffcfffffaffff8ffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffff8ffffafffffcffffff4ffffeff5fff2f1fff
    ff1ffff2ff5ffeffff4fffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcfffffff4ffffeff5ff2ff1fff
    ff1ffff2ff5ffefffff4ffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcffffff4fffffeff5ff2ff1fff
    fff1fff2fff5ffeffff4ffffcfffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffafffffcffffff4ffffeff5fff2f1ffff
    fff1fff2fff5ffeffff4fffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcfffffff4ffffeff5fff2f1ffff
    fff1ffff2ff5ffefffff4ffffcfffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffafffffcffffff4fffffeff5ff2ff1ffff
    ffff1fff2fff5ffeffff4fffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcfffffff4ffffeff5fff2f1fffff
    ffff1fff2fff5ffeffff4fffffcfffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffafffffcfffffff4ffffeff5fff2f1fffff
    ffff1ffff2ff5fffeffff4fffffcffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffaffffcfffffff4ffffefff5ff2ff1fffff
    fffff1fff2fff5ffeffff4fffffcfffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffafffffcfffffff4ffffeff5fff2f1ffffff
    fffff1fff2fff5ffefffff4fffffcffffafffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8fffffaffffcfffffff4fffffeff5fff2f1ffffff
    fffff1ffff2fff5ffeffff4fffffcfffffaffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8ffffafffffcfffffff4ffffeff5fff2ff1ffffff
    ffffff1fff2fff5ffefffff4fffffcfffffaffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8ffffafffffcfffffff4fffffeff5fff2f1fffffff
    ffffff1ffff2ff5fffeffff4fffffcfffffafffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8fffffafffffcfffffff4ffffefff5ff2ff1fffffff
    fffffff1fff2fff5ffefffff4fffffcfffffafffff8fffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffff8fffffafffffcfffffff4fffffeff5fff2f1ffffffff
    fffffff1ffff2ff5fffeffff4ffffffcfffffaffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8ffffafffffcffffffff4ffffefff5ff2ff1ffffffff
    ffffffff1fff2fff5ffefffff4fffffcffffffaffff8ffffffff6fffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffff8ffffaffffffcfffffff4fffffeff5fff2f1fffffffff
    ffffffff1ffff2ff5fffefffff4fffffcfffffafffff8ffffffff66fffffffffffffffffffffffffffffffffffffffffffffffffff66ffffff8fffffafffffcfffffff4fffffefff5ff2ff1fffffffff
    fffffffff1fff2fff5ffefffff4ffffffcfffffafffff8fffffffff6fffffffffffffffffffffffffffffffffffffffffffffffff6fffffff8fffffafffffcffffffff4fffffeff5fff2f1ffffffffff
    fffffffff1ffff2fff5ffefffff4ffffffcfffffafffff8fffffffff6fffffffffffffffffffffffffffffffffffffffffffffff6fffffff8fffffafffffcffffffff4fffffeff5fff2ff1ffffffffff
    ffffffffff1fff2fff5fffefffff4fffffcffffffafffff88ffffffff66fffffffffffffffffffffffffffffffffffffffffff66ffffff88fffffaffffffcfffffff4fffffefff5fff2f1fffffffffff
    ffffffffff1ffff2fff5ffefffff4ffffffcffffffaffffff8fffffffff66fffffffffffffffffffffffffffffffffffffff66fffffff8ffffffaffffffcffffffff4fffffeff5fff2ff1fffffffffff
    fffffffffff1fff2fff5fffefffff4ffffffcffffffaffffff8ffffffffff66fffffffffffffffffffffffffffffffffff66ffffffff8ffffffaffffffcffffffff4fffffefff5fff2f1ffffffffffff
    fffffffffff1ffff2fff5fffefffff4ffffffcffffffaafffff88ffffffffff66fffffffffffffffffffffffffffffff66ffffffff88fffffaaffffffcffffffff4fffffefff5fff2ff1ffffffffffff
    ffffffffffff1ffff2fff5ffeffffff4ffffffcfffffffaffffff8fffffffffff666fffffffffffffffffffffffff666fffffffff8ffffffafffffffcffffffff4ffffffeff5fff2ff1fffffffffffff
    fffffffffffff1fff2ffff5ffeffffff4ffffffcfffffffaffffff88ffffffffffff666fffffffffffffffffff666ffffffffff88ffffffafffffffcffffffff4ffffffeff5ffff2f1ffffffffffffff
    fffffffffffff1ffff2fff5fffeffffff4ffffffcfffffffaaffffff88fffffffffffff6666666666666666666fffffffffff88ffffffaafffffffcffffffff4ffffffefff5fff2ff1ffffffffffffff
    ffffffffffffff1ffff2fff5fffeffffff4ffffffccfffffffafffffff88fffffffffffffffffffffffffffffffffffffff88fffffffafffffffccffffffff4ffffffefff5fff2ff1fffffffffffffff
    fffffffffffffff1fff2ffff5fffeffffff4fffffffcfffffffaafffffff888fffffffffffffffffffffffffffffffff888fffffffaafffffffcfffffffff4ffffffefff5ffff2f1ffffffffffffffff
    fffffffffffffff1ffff2ffff5fffeffffff4fffffffcffffffffaaffffffff888fffffffffffffffffffffffffff888ffffffffaaffffffffcfffffffff4ffffffefff5ffff2ff1ffffffffffffffff
    ffffffffffffffff1ffff2fff5ffffeffffff4fffffffccffffffffaafffffffff8888fffffffffffffffffff8888fffffffffaaffffffffccfffffffff4ffffffeffff5fff2ff1fffffffffffffffff
    fffffffffffffffff1ffff2fff5ffffeffffff4ffffffffcfffffffffaafffffffffff8888888888888888888fffffffffffaafffffffffcffffffffff4ffffffeffff5fff2ff1ffffffffffffffffff
    ffffffffffffffffff1fff2ffff5ffffeffffff4ffffffffccfffffffffaaafffffffffffffffffffffffffffffffffffaaafffffffffccffffffffff4ffffffeffff5ffff2f1fffffffffffffffffff
    fffffffffffffffffff1fff2ffff5ffffeffffff4fffffffffccffffffffffaaafffffffffffffffffffffffffffffaaaffffffffffccfffffffffff4ffffffeffff5ffff2f1ffffffffffffffffffff
    ffffffffffffffffffff1fff2ffff5ffffeffffff44fffffffffccfffffffffffaaaafffffffffffffffffffffaaaafffffffffffccfffffffffff44ffffffeffff5ffff2f1fffffffffffffffffffff
    ffffffffffffffffffff1ffff2ffff5ffffefffffff4ffffffffffccfffffffffffffaaaaaaaaaaaaaaaaaaaaafffffffffffffccffffffffffff4fffffffeffff5ffff2ff1fffffffffffffffffffff
    fffffffffffffffffffff1ffff2ffff5ffffefffffff44ffffffffffccfffffffffffffffffffffffffffffffffffffffffffccffffffffffff44fffffffeffff5ffff2ff1ffffffffffffffffffffff
    ffffffffffffffffffffff1ffff2ffff55fffeffffffff4fffffffffffcccfffffffffffffffffffffffffffffffffffffcccfffffffffffff4ffffffffefff55ffff2ff1fffffffffffffffffffffff
    fffffffffffffffffffffff1ffff2fffff5fffeefffffff44ffffffffffffcccfffffffffffffffffffffffffffffffcccffffffffffffff44fffffffeefff5fffff2ff1ffffffffffffffffffffffff
    ffffffffffffffffffffffff1ffff2fffff5ffffeffffffff44fffffffffffffcccccfffffffffffffffffffffcccccfffffffffffffff44ffffffffeffff5fffff2ff1fffffffffffffffffffffffff
    fffffffffffffffffffffffff11fff2fffff55fffeeffffffff44ffffffffffffffffcccccccccccccccccccccffffffffffffffffff44ffffffffeefff55fffff2f11ffffffffffffffffffffffffff
    fffffffffffffffffffffffffff1fff22fffff5ffffefffffffff44fffffffffffffffffffffffffffffffffffffffffffffffffff44fffffffffeffff5fffff22f1ffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffff1ffff2fffff5ffffeefffffffff444fffffffffffffffffffffffffffffffffffffffffffff444fffffffffeeffff5fffff2ff1fffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffff1ffff2fffff55ffffeeffffffffff444fffffffffffffffffffffffffffffffffffffff444ffffffffffeeffff55fffff2ff1ffffffffffffffffffffffffffffff
    `)
monthList = [
"january",
"february",
"march",
"april",
"may",
"june",
"july",
"august",
"september",
"october",
"november",
"december"
]
birthstoneList = [
"Garnet",
"Amethyst",
"Aquamarine",
"Diamond",
"Emerald",
"Pearl",
"Ruby",
"Peridot",
"Sapphire",
"Opal",
"Topaz",
"Turquoise"
]
flowerList = [
"Snowdrop",
"Violet",
"Daffodil",
"Daisy",
"Lily of the Valley",
"Rose",
"Larkspur",
"Poppy",
"Aster",
"Marigold",
"Chrysanthemum",
"Holly"
]
game.splash("Birthstone or Flower?")
let Month = game.askForString("What month were you born in?", 9)
let Answer = game.askForNumber("Birthstone (1) or Flower (2)", 1)
if (Answer == 1) {
    birthstones(Month, "abc")
} else if (Answer == 2) {
	
} else {
    game.splash("Error. Try Again")
}
game.splash("Thanks for playing!")
game.reset()
